///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace UmlautTecDraw
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the UmlautTecDrawRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("1ce5fbff-db89-4e66-95b6-594f92b9d000")]
    public partial class UmlautTecDrawRepository : RepoGenBaseFolder
    {
        static UmlautTecDrawRepository instance = new UmlautTecDrawRepository();
        UmlautTecDrawRepositoryFolders.MainWinAppFolder _mainwin;
        UmlautTecDrawRepositoryFolders.UmlautTecDrawAppFolder _umlauttecdraw;
        UmlautTecDrawRepositoryFolders.LineFormAppFolder _lineform;
        UmlautTecDrawRepositoryFolders.List1000AppFolder _list1000;
        UmlautTecDrawRepositoryFolders.UmlautTecDraw1AppFolder _umlauttecdraw1;
        UmlautTecDrawRepositoryFolders.SaveAppFolder _save;
        UmlautTecDrawRepositoryFolders.BatchConverterFormAppFolder _batchconverterform;

        /// <summary>
        /// Gets the singleton class instance representing the UmlautTecDrawRepository element repository.
        /// </summary>
        [RepositoryFolder("1ce5fbff-db89-4e66-95b6-594f92b9d000")]
        public static UmlautTecDrawRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public UmlautTecDrawRepository() 
            : base("UmlautTecDrawRepository", "/", null, 0, false, "1ce5fbff-db89-4e66-95b6-594f92b9d000", ".\\RepositoryImages\\UmlautTecDrawRepository1ce5fbff.rximgres")
        {
            _mainwin = new UmlautTecDrawRepositoryFolders.MainWinAppFolder(this);
            _umlauttecdraw = new UmlautTecDrawRepositoryFolders.UmlautTecDrawAppFolder(this);
            _lineform = new UmlautTecDrawRepositoryFolders.LineFormAppFolder(this);
            _list1000 = new UmlautTecDrawRepositoryFolders.List1000AppFolder(this);
            _umlauttecdraw1 = new UmlautTecDrawRepositoryFolders.UmlautTecDraw1AppFolder(this);
            _save = new UmlautTecDrawRepositoryFolders.SaveAppFolder(this);
            _batchconverterform = new UmlautTecDrawRepositoryFolders.BatchConverterFormAppFolder(this);
        }

#region Variables

        string _ColorSelection = "ff009900";

        /// <summary>
        /// Gets or sets the value of variable ColorSelection.
        /// </summary>
        [TestVariable("1e2b8a30-b9f0-4098-96ce-a39292274bb1")]
        public string ColorSelection
        {
            get { return _ColorSelection; }
            set { _ColorSelection = value; }
        }

        string _LineTypeSelection = "Broken-dash";

        /// <summary>
        /// Gets or sets the value of variable LineTypeSelection.
        /// </summary>
        [TestVariable("5e16c311-ccee-4c1a-bc9f-5c92a0a79c0a")]
        public string LineTypeSelection
        {
            get { return _LineTypeSelection; }
            set { _LineTypeSelection = value; }
        }

        string _LineWidth = "0.35";

        /// <summary>
        /// Gets or sets the value of variable LineWidth.
        /// </summary>
        [TestVariable("1c46164b-33a6-4a48-9f91-1750ea854bf8")]
        public string LineWidth
        {
            get { return _LineWidth; }
            set { _LineWidth = value; }
        }

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("1ce5fbff-db89-4e66-95b6-594f92b9d000")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The MainWin folder.
        /// </summary>
        [RepositoryFolder("64afebcf-5647-4f0c-afc5-e42676277f36")]
        public virtual UmlautTecDrawRepositoryFolders.MainWinAppFolder MainWin
        {
            get { return _mainwin; }
        }

        /// <summary>
        /// The UmlautTecDraw folder.
        /// </summary>
        [RepositoryFolder("cd567c78-0485-43b8-880b-e4bd0e95838f")]
        public virtual UmlautTecDrawRepositoryFolders.UmlautTecDrawAppFolder UmlautTecDraw
        {
            get { return _umlauttecdraw; }
        }

        /// <summary>
        /// The LineForm folder.
        /// </summary>
        [RepositoryFolder("c53cc27e-ba70-49ca-8590-b43dd408a86a")]
        public virtual UmlautTecDrawRepositoryFolders.LineFormAppFolder LineForm
        {
            get { return _lineform; }
        }

        /// <summary>
        /// The List1000 folder.
        /// </summary>
        [RepositoryFolder("9787436e-a8b0-4425-b2b2-31b65405ebec")]
        public virtual UmlautTecDrawRepositoryFolders.List1000AppFolder List1000
        {
            get { return _list1000; }
        }

        /// <summary>
        /// The UmlautTecDraw1 folder.
        /// </summary>
        [RepositoryFolder("a0f5c70e-9db0-439b-b8e9-adeb8b81fb1b")]
        public virtual UmlautTecDrawRepositoryFolders.UmlautTecDraw1AppFolder UmlautTecDraw1
        {
            get { return _umlauttecdraw1; }
        }

        /// <summary>
        /// The Save folder.
        /// </summary>
        [RepositoryFolder("d9e9eb8d-7834-4143-a7a2-8fe6701a060d")]
        public virtual UmlautTecDrawRepositoryFolders.SaveAppFolder Save
        {
            get { return _save; }
        }

        /// <summary>
        /// The BatchConverterForm folder.
        /// </summary>
        [RepositoryFolder("95d8ea81-897e-4b08-b2c0-b911cb120c2e")]
        public virtual UmlautTecDrawRepositoryFolders.BatchConverterFormAppFolder BatchConverterForm
        {
            get { return _batchconverterform; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class UmlautTecDrawRepositoryFolders
    {
        /// <summary>
        /// The MainWinAppFolder folder.
        /// </summary>
        [RepositoryFolder("64afebcf-5647-4f0c-afc5-e42676277f36")]
        public partial class MainWinAppFolder : RepoGenBaseFolder
        {
            UmlautTecDrawRepositoryFolders.Canvas1Folder _canvas1;
            UmlautTecDrawRepositoryFolders.PropertyFolder _property;
            PushButtonInfoClass _pushbuttonInfo;
            RepoItemInfo _pushbutton1Info;
            RepoItemInfo _fileInfo;

            /// <summary>
            /// Creates a new MainWin  folder.
            /// </summary>
            public MainWinAppFolder(RepoGenBaseFolder parentFolder) :
                    base("MainWin", "/form[@controlname='MainWin']", parentFolder, 30000, null, true, "64afebcf-5647-4f0c-afc5-e42676277f36", "")
            {
                _canvas1 = new UmlautTecDrawRepositoryFolders.Canvas1Folder(this);
                _property = new UmlautTecDrawRepositoryFolders.PropertyFolder(this);
                _pushbuttonInfo = new PushButtonInfoClass(this);
                _pushbutton1Info = new RepoItemInfo(this, "PushButton1", "?/?/toolbar[@controlname='Draw']/button[2]", "?/?/toolbar[@controlname='Draw']/button[2]", 30000, null, "7e250af7-460b-48d5-aa32-56e81b90a6b9");
                _fileInfo = new RepoItemInfo(this, "File", "?/?/menubar[@controlname='m_mainMenu']/menuitem[@accessiblename='File']", ".//menuitem[@accessiblename='File']", 30000, null, "4e6ca508-690b-4696-91c5-25de48137398");
            }

            /// <summary>
            /// The PushButtonInfoClass folder.
            /// </summary>
            [RepositoryItemInfo("674d446d-2ab6-447d-b2ba-7cad0773744e")]
            public class PushButtonInfoClass : RepoItemInfo
            {
                /// <summary>
                /// PushButtonInfoClass class constructor.
                /// </summary>
                public PushButtonInfoClass(RepoGenBaseFolder parentFolder)
                    : base(parentFolder, "PushButton", "?/?/toolbar[@controlname='Draw']/button[3]", 30000, null, "674d446d-2ab6-447d-b2ba-7cad0773744e")
                { }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <returns>The Screenshot1 image.</returns>
                [RepositoryImage("cd126bf7-e0fe-4f40-87ec-036df8dcf90c")]
                public CompressedImage GetScreenshot1()
                {
                    return GetImage("cd126bf7-e0fe-4f40-87ec-036df8dcf90c");
                }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("cd126bf7-e0fe-4f40-87ec-036df8dcf90c")]
                public CompressedImage GetScreenshot1(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("cd126bf7-e0fe-4f40-87ec-036df8dcf90c", cropRect);
                }

                /// <summary>
                /// Gets the Screenshot2 item image.
                /// </summary>
                /// <returns>The Screenshot2 image.</returns>
                [RepositoryImage("fbc4f9b1-35d6-48e1-8180-ee6558ca29bc")]
                public CompressedImage GetScreenshot2()
                {
                    return GetImage("fbc4f9b1-35d6-48e1-8180-ee6558ca29bc");
                }

                /// <summary>
                /// Gets the Screenshot2 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("fbc4f9b1-35d6-48e1-8180-ee6558ca29bc")]
                public CompressedImage GetScreenshot2(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("fbc4f9b1-35d6-48e1-8180-ee6558ca29bc", cropRect);
                }
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("64afebcf-5647-4f0c-afc5-e42676277f36")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("64afebcf-5647-4f0c-afc5-e42676277f36")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The PushButton item.
            /// </summary>
            [RepositoryItem("674d446d-2ab6-447d-b2ba-7cad0773744e")]
            public virtual Ranorex.Button PushButton
            {
                get
                {
                    return _pushbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The PushButton item info.
            /// </summary>
            [RepositoryItemInfo("674d446d-2ab6-447d-b2ba-7cad0773744e")]
            public virtual PushButtonInfoClass PushButtonInfo
            {
                get
                {
                    return _pushbuttonInfo;
                }
            }

            /// <summary>
            /// The PushButton1 item.
            /// </summary>
            [RepositoryItem("7e250af7-460b-48d5-aa32-56e81b90a6b9")]
            public virtual Ranorex.Button PushButton1
            {
                get
                {
                    return _pushbutton1Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The PushButton1 item info.
            /// </summary>
            [RepositoryItemInfo("7e250af7-460b-48d5-aa32-56e81b90a6b9")]
            public virtual RepoItemInfo PushButton1Info
            {
                get
                {
                    return _pushbutton1Info;
                }
            }

            /// <summary>
            /// The File item.
            /// </summary>
            [RepositoryItem("4e6ca508-690b-4696-91c5-25de48137398")]
            public virtual Ranorex.MenuItem File
            {
                get
                {
                    return _fileInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The File item info.
            /// </summary>
            [RepositoryItemInfo("4e6ca508-690b-4696-91c5-25de48137398")]
            public virtual RepoItemInfo FileInfo
            {
                get
                {
                    return _fileInfo;
                }
            }

            /// <summary>
            /// The Canvas1 folder.
            /// </summary>
            [RepositoryFolder("0d233b49-ad24-4d63-9f87-540d8d9ad70c")]
            public virtual UmlautTecDrawRepositoryFolders.Canvas1Folder Canvas1
            {
                get { return _canvas1; }
            }

            /// <summary>
            /// The Property folder.
            /// </summary>
            [RepositoryFolder("5418f132-bb1f-4cff-85f5-015c1956874e")]
            public virtual UmlautTecDrawRepositoryFolders.PropertyFolder Property
            {
                get { return _property; }
            }
        }

        /// <summary>
        /// The Canvas1Folder folder.
        /// </summary>
        [RepositoryFolder("0d233b49-ad24-4d63-9f87-540d8d9ad70c")]
        public partial class Canvas1Folder : RepoGenBaseFolder
        {
            CanvasCtrlInfoClass _canvasctrlInfo;

            /// <summary>
            /// Creates a new Canvas1  folder.
            /// </summary>
            public Canvas1Folder(RepoGenBaseFolder parentFolder) :
                    base("Canvas1", ".//tabpage[@controlname='doc1']/element[@controlname='CanvasCtrl']", parentFolder, 30000, null, false, "0d233b49-ad24-4d63-9f87-540d8d9ad70c", "")
            {
                _canvasctrlInfo = new CanvasCtrlInfoClass(this);
            }

            /// <summary>
            /// The CanvasCtrlInfoClass folder.
            /// </summary>
            [RepositoryItemInfo("109229b9-aedd-496f-a39d-06306b80eada")]
            public class CanvasCtrlInfoClass : RepoItemInfo
            {
                /// <summary>
                /// CanvasCtrlInfoClass class constructor.
                /// </summary>
                public CanvasCtrlInfoClass(RepoGenBaseFolder parentFolder)
                    : base(parentFolder, "CanvasCtrl", "", 30000, null, "109229b9-aedd-496f-a39d-06306b80eada")
                { }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <returns>The Screenshot1 image.</returns>
                [RepositoryImage("c60ca772-673f-4733-9bec-943633965a62")]
                public CompressedImage GetScreenshot1()
                {
                    return GetImage("c60ca772-673f-4733-9bec-943633965a62");
                }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("c60ca772-673f-4733-9bec-943633965a62")]
                public CompressedImage GetScreenshot1(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("c60ca772-673f-4733-9bec-943633965a62", cropRect);
                }

                /// <summary>
                /// Gets the Screenshot10 item image.
                /// </summary>
                /// <returns>The Screenshot10 image.</returns>
                [RepositoryImage("1a812144-290f-4057-98a6-9b8a163ccb5d")]
                public CompressedImage GetScreenshot10()
                {
                    return GetImage("1a812144-290f-4057-98a6-9b8a163ccb5d");
                }

                /// <summary>
                /// Gets the Screenshot10 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("1a812144-290f-4057-98a6-9b8a163ccb5d")]
                public CompressedImage GetScreenshot10(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("1a812144-290f-4057-98a6-9b8a163ccb5d", cropRect);
                }

                /// <summary>
                /// Gets the Screenshot11 item image.
                /// </summary>
                /// <returns>The Screenshot11 image.</returns>
                [RepositoryImage("0470ceda-9518-487f-a5ff-3c557733676b")]
                public CompressedImage GetScreenshot11()
                {
                    return GetImage("0470ceda-9518-487f-a5ff-3c557733676b");
                }

                /// <summary>
                /// Gets the Screenshot11 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("0470ceda-9518-487f-a5ff-3c557733676b")]
                public CompressedImage GetScreenshot11(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("0470ceda-9518-487f-a5ff-3c557733676b", cropRect);
                }

                /// <summary>
                /// Gets the Screenshot12 item image.
                /// </summary>
                /// <returns>The Screenshot12 image.</returns>
                [RepositoryImage("cc74fc6d-b721-4b57-9a32-cef04f41686c")]
                public CompressedImage GetScreenshot12()
                {
                    return GetImage("cc74fc6d-b721-4b57-9a32-cef04f41686c");
                }

                /// <summary>
                /// Gets the Screenshot12 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("cc74fc6d-b721-4b57-9a32-cef04f41686c")]
                public CompressedImage GetScreenshot12(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("cc74fc6d-b721-4b57-9a32-cef04f41686c", cropRect);
                }

                /// <summary>
                /// Gets the Screenshot13 item image.
                /// </summary>
                /// <returns>The Screenshot13 image.</returns>
                [RepositoryImage("a0656ead-f959-4ee4-b418-bc52098c0a44")]
                public CompressedImage GetScreenshot13()
                {
                    return GetImage("a0656ead-f959-4ee4-b418-bc52098c0a44");
                }

                /// <summary>
                /// Gets the Screenshot13 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("a0656ead-f959-4ee4-b418-bc52098c0a44")]
                public CompressedImage GetScreenshot13(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("a0656ead-f959-4ee4-b418-bc52098c0a44", cropRect);
                }

                /// <summary>
                /// Gets the Screenshot2 item image.
                /// </summary>
                /// <returns>The Screenshot2 image.</returns>
                [RepositoryImage("c0a74849-f1e1-42f3-8238-4c887601f8fe")]
                public CompressedImage GetScreenshot2()
                {
                    return GetImage("c0a74849-f1e1-42f3-8238-4c887601f8fe");
                }

                /// <summary>
                /// Gets the Screenshot2 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("c0a74849-f1e1-42f3-8238-4c887601f8fe")]
                public CompressedImage GetScreenshot2(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("c0a74849-f1e1-42f3-8238-4c887601f8fe", cropRect);
                }

                /// <summary>
                /// Gets the Screenshot3 item image.
                /// </summary>
                /// <returns>The Screenshot3 image.</returns>
                [RepositoryImage("d7f0aaf6-fa08-447a-9cf8-ec8db7608131")]
                public CompressedImage GetScreenshot3()
                {
                    return GetImage("d7f0aaf6-fa08-447a-9cf8-ec8db7608131");
                }

                /// <summary>
                /// Gets the Screenshot3 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("d7f0aaf6-fa08-447a-9cf8-ec8db7608131")]
                public CompressedImage GetScreenshot3(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("d7f0aaf6-fa08-447a-9cf8-ec8db7608131", cropRect);
                }

                /// <summary>
                /// Gets the Screenshot4 item image.
                /// </summary>
                /// <returns>The Screenshot4 image.</returns>
                [RepositoryImage("ec3a5de9-f3f8-4d45-89ed-e6fa0a7aae47")]
                public CompressedImage GetScreenshot4()
                {
                    return GetImage("ec3a5de9-f3f8-4d45-89ed-e6fa0a7aae47");
                }

                /// <summary>
                /// Gets the Screenshot4 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("ec3a5de9-f3f8-4d45-89ed-e6fa0a7aae47")]
                public CompressedImage GetScreenshot4(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("ec3a5de9-f3f8-4d45-89ed-e6fa0a7aae47", cropRect);
                }

                /// <summary>
                /// Gets the Screenshot5 item image.
                /// </summary>
                /// <returns>The Screenshot5 image.</returns>
                [RepositoryImage("089289a2-49e1-4014-920a-64c27ef9ba25")]
                public CompressedImage GetScreenshot5()
                {
                    return GetImage("089289a2-49e1-4014-920a-64c27ef9ba25");
                }

                /// <summary>
                /// Gets the Screenshot5 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("089289a2-49e1-4014-920a-64c27ef9ba25")]
                public CompressedImage GetScreenshot5(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("089289a2-49e1-4014-920a-64c27ef9ba25", cropRect);
                }

                /// <summary>
                /// Gets the Screenshot6 item image.
                /// </summary>
                /// <returns>The Screenshot6 image.</returns>
                [RepositoryImage("626e4a46-8c9d-4719-a187-d42b61ddecb1")]
                public CompressedImage GetScreenshot6()
                {
                    return GetImage("626e4a46-8c9d-4719-a187-d42b61ddecb1");
                }

                /// <summary>
                /// Gets the Screenshot6 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("626e4a46-8c9d-4719-a187-d42b61ddecb1")]
                public CompressedImage GetScreenshot6(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("626e4a46-8c9d-4719-a187-d42b61ddecb1", cropRect);
                }

                /// <summary>
                /// Gets the Screenshot7 item image.
                /// </summary>
                /// <returns>The Screenshot7 image.</returns>
                [RepositoryImage("fd07e0eb-18ef-4485-9ccb-22f0c14bc5ca")]
                public CompressedImage GetScreenshot7()
                {
                    return GetImage("fd07e0eb-18ef-4485-9ccb-22f0c14bc5ca");
                }

                /// <summary>
                /// Gets the Screenshot7 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("fd07e0eb-18ef-4485-9ccb-22f0c14bc5ca")]
                public CompressedImage GetScreenshot7(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("fd07e0eb-18ef-4485-9ccb-22f0c14bc5ca", cropRect);
                }

                /// <summary>
                /// Gets the Screenshot8 item image.
                /// </summary>
                /// <returns>The Screenshot8 image.</returns>
                [RepositoryImage("4b6a7033-21b9-4e7c-9129-e91ad07d0e6d")]
                public CompressedImage GetScreenshot8()
                {
                    return GetImage("4b6a7033-21b9-4e7c-9129-e91ad07d0e6d");
                }

                /// <summary>
                /// Gets the Screenshot8 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("4b6a7033-21b9-4e7c-9129-e91ad07d0e6d")]
                public CompressedImage GetScreenshot8(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("4b6a7033-21b9-4e7c-9129-e91ad07d0e6d", cropRect);
                }

                /// <summary>
                /// Gets the Screenshot9 item image.
                /// </summary>
                /// <returns>The Screenshot9 image.</returns>
                [RepositoryImage("702adc86-733b-418d-807b-0f914cc32a96")]
                public CompressedImage GetScreenshot9()
                {
                    return GetImage("702adc86-733b-418d-807b-0f914cc32a96");
                }

                /// <summary>
                /// Gets the Screenshot9 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("702adc86-733b-418d-807b-0f914cc32a96")]
                public CompressedImage GetScreenshot9(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("702adc86-733b-418d-807b-0f914cc32a96", cropRect);
                }
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("0d233b49-ad24-4d63-9f87-540d8d9ad70c")]
            public virtual Ranorex.Unknown Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("0d233b49-ad24-4d63-9f87-540d8d9ad70c")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The CanvasCtrl item.
            /// </summary>
            [RepositoryItem("109229b9-aedd-496f-a39d-06306b80eada")]
            public virtual Ranorex.Unknown CanvasCtrl
            {
                get
                {
                    return _canvasctrlInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The CanvasCtrl item info.
            /// </summary>
            [RepositoryItemInfo("109229b9-aedd-496f-a39d-06306b80eada")]
            public virtual CanvasCtrlInfoClass CanvasCtrlInfo
            {
                get
                {
                    return _canvasctrlInfo;
                }
            }
        }

        /// <summary>
        /// The PropertyFolder folder.
        /// </summary>
        [RepositoryFolder("5418f132-bb1f-4cff-85f5-015c1956874e")]
        public partial class PropertyFolder : RepoGenBaseFolder
        {
            RepoItemInfo _toolstripcomboboxcontrolInfo;
            RepoItemInfo _toolstripcomboboxcontrol1Info;
            RepoItemInfo _toolstripcomboboxcontrol2Info;

            /// <summary>
            /// Creates a new Property  folder.
            /// </summary>
            public PropertyFolder(RepoGenBaseFolder parentFolder) :
                    base("Property", "element[@controlname='RightTabControl']/tabpage[@controlname='Property']", parentFolder, 30000, null, false, "5418f132-bb1f-4cff-85f5-015c1956874e", "")
            {
                _toolstripcomboboxcontrolInfo = new RepoItemInfo(this, "ToolStripComboBoxControl", ".//toolbar[@controlname='LineGraphicProperty_1']/combobox[@controltypename='ToolStripComboBoxControl']", "", 30000, null, "74850a61-0e0c-44ed-aa51-307466baa1d6");
                _toolstripcomboboxcontrol1Info = new RepoItemInfo(this, "ToolStripComboBoxControl1", ".//toolbar[@controlname='LineGraphicProperty_2']/combobox[@controltypename='ToolStripComboBoxControl']", "", 30000, null, "943118b0-cd42-4895-9752-d3c3a83a9977");
                _toolstripcomboboxcontrol2Info = new RepoItemInfo(this, "ToolStripComboBoxControl2", ".//toolbar[@controlname='LineGraphicProperty_3']/combobox[@controltypename='ToolStripComboBoxControl']", "", 30000, null, "5f906ea4-d574-43d9-b709-c552125d5a9a");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("5418f132-bb1f-4cff-85f5-015c1956874e")]
            public virtual Ranorex.TabPage Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("5418f132-bb1f-4cff-85f5-015c1956874e")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ToolStripComboBoxControl item.
            /// </summary>
            [RepositoryItem("74850a61-0e0c-44ed-aa51-307466baa1d6")]
            public virtual Ranorex.ComboBox ToolStripComboBoxControl
            {
                get
                {
                    return _toolstripcomboboxcontrolInfo.CreateAdapter<Ranorex.ComboBox>(true);
                }
            }

            /// <summary>
            /// The ToolStripComboBoxControl item info.
            /// </summary>
            [RepositoryItemInfo("74850a61-0e0c-44ed-aa51-307466baa1d6")]
            public virtual RepoItemInfo ToolStripComboBoxControlInfo
            {
                get
                {
                    return _toolstripcomboboxcontrolInfo;
                }
            }

            /// <summary>
            /// The ToolStripComboBoxControl1 item.
            /// </summary>
            [RepositoryItem("943118b0-cd42-4895-9752-d3c3a83a9977")]
            public virtual Ranorex.ComboBox ToolStripComboBoxControl1
            {
                get
                {
                    return _toolstripcomboboxcontrol1Info.CreateAdapter<Ranorex.ComboBox>(true);
                }
            }

            /// <summary>
            /// The ToolStripComboBoxControl1 item info.
            /// </summary>
            [RepositoryItemInfo("943118b0-cd42-4895-9752-d3c3a83a9977")]
            public virtual RepoItemInfo ToolStripComboBoxControl1Info
            {
                get
                {
                    return _toolstripcomboboxcontrol1Info;
                }
            }

            /// <summary>
            /// The ToolStripComboBoxControl2 item.
            /// </summary>
            [RepositoryItem("5f906ea4-d574-43d9-b709-c552125d5a9a")]
            public virtual Ranorex.ComboBox ToolStripComboBoxControl2
            {
                get
                {
                    return _toolstripcomboboxcontrol2Info.CreateAdapter<Ranorex.ComboBox>(true);
                }
            }

            /// <summary>
            /// The ToolStripComboBoxControl2 item info.
            /// </summary>
            [RepositoryItemInfo("5f906ea4-d574-43d9-b709-c552125d5a9a")]
            public virtual RepoItemInfo ToolStripComboBoxControl2Info
            {
                get
                {
                    return _toolstripcomboboxcontrol2Info;
                }
            }
        }

        /// <summary>
        /// The UmlautTecDrawAppFolder folder.
        /// </summary>
        [RepositoryFolder("cd567c78-0485-43b8-880b-e4bd0e95838f")]
        public partial class UmlautTecDrawAppFolder : RepoGenBaseFolder
        {
            UmlautTecDrawRepositoryFolders.NewRootedFolderFolder _newrootedfolder;
            ThreePointRectangleInfoClass _threepointrectangleInfo;

            /// <summary>
            /// Creates a new UmlautTecDraw  folder.
            /// </summary>
            public UmlautTecDrawAppFolder(RepoGenBaseFolder parentFolder) :
                    base("UmlautTecDraw", "/toolbar", parentFolder, 30000, null, true, "cd567c78-0485-43b8-880b-e4bd0e95838f", "")
            {
                _newrootedfolder = new UmlautTecDrawRepositoryFolders.NewRootedFolderFolder(this);
                _threepointrectangleInfo = new ThreePointRectangleInfoClass(this);
            }

            /// <summary>
            /// The ThreePointRectangleInfoClass folder.
            /// </summary>
            [RepositoryItemInfo("adaf12d0-ab0d-4e0f-88a6-f5e4136c0764")]
            public class ThreePointRectangleInfoClass : RepoItemInfo
            {
                /// <summary>
                /// ThreePointRectangleInfoClass class constructor.
                /// </summary>
                public ThreePointRectangleInfoClass(RepoGenBaseFolder parentFolder)
                    : base(parentFolder, "ThreePointRectangle", "contextmenu/menuitem[@accessiblename='Three Point Rectangle']", 30000, null, "adaf12d0-ab0d-4e0f-88a6-f5e4136c0764")
                { }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <returns>The Screenshot1 image.</returns>
                [RepositoryImage("351c9949-47cf-4dd0-8028-a4c62925cc94")]
                public CompressedImage GetScreenshot1()
                {
                    return GetImage("351c9949-47cf-4dd0-8028-a4c62925cc94");
                }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("351c9949-47cf-4dd0-8028-a4c62925cc94")]
                public CompressedImage GetScreenshot1(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("351c9949-47cf-4dd0-8028-a4c62925cc94", cropRect);
                }
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("cd567c78-0485-43b8-880b-e4bd0e95838f")]
            public virtual Ranorex.ToolBar Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.ToolBar>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("cd567c78-0485-43b8-880b-e4bd0e95838f")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ThreePointRectangle item.
            /// </summary>
            [RepositoryItem("adaf12d0-ab0d-4e0f-88a6-f5e4136c0764")]
            public virtual Ranorex.MenuItem ThreePointRectangle
            {
                get
                {
                    return _threepointrectangleInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The ThreePointRectangle item info.
            /// </summary>
            [RepositoryItemInfo("adaf12d0-ab0d-4e0f-88a6-f5e4136c0764")]
            public virtual ThreePointRectangleInfoClass ThreePointRectangleInfo
            {
                get
                {
                    return _threepointrectangleInfo;
                }
            }

            /// <summary>
            /// The NewRootedFolder folder.
            /// </summary>
            [RepositoryFolder("70b307e8-731d-44b9-9a68-9f5c3001dd87")]
            public virtual UmlautTecDrawRepositoryFolders.NewRootedFolderFolder NewRootedFolder
            {
                get { return _newrootedfolder; }
            }
        }

        /// <summary>
        /// The NewRootedFolderFolder folder.
        /// </summary>
        [RepositoryFolder("70b307e8-731d-44b9-9a68-9f5c3001dd87")]
        public partial class NewRootedFolderFolder : RepoGenBaseFolder
        {
            RepoItemInfo _polylineInfo;

            /// <summary>
            /// Creates a new NewRootedFolder  folder.
            /// </summary>
            public NewRootedFolderFolder(RepoGenBaseFolder parentFolder) :
                    base("NewRootedFolder", "?/?/menuitem[@accessiblename='PolyLine']", parentFolder, 30000, null, false, "70b307e8-731d-44b9-9a68-9f5c3001dd87", "")
            {
                _polylineInfo = new RepoItemInfo(this, "PolyLine", "", "", 30000, null, "81d6e90a-58d5-4026-9587-d44b08b8bb74");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("70b307e8-731d-44b9-9a68-9f5c3001dd87")]
            public virtual Ranorex.MenuItem Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("70b307e8-731d-44b9-9a68-9f5c3001dd87")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The PolyLine item.
            /// </summary>
            [RepositoryItem("81d6e90a-58d5-4026-9587-d44b08b8bb74")]
            public virtual Ranorex.MenuItem PolyLine
            {
                get
                {
                    return _polylineInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The PolyLine item info.
            /// </summary>
            [RepositoryItemInfo("81d6e90a-58d5-4026-9587-d44b08b8bb74")]
            public virtual RepoItemInfo PolyLineInfo
            {
                get
                {
                    return _polylineInfo;
                }
            }
        }

        /// <summary>
        /// The LineFormAppFolder folder.
        /// </summary>
        [RepositoryFolder("c53cc27e-ba70-49ca-8590-b43dd408a86a")]
        public partial class LineFormAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _closeInfo;
            RepoItemInfo _gbxpoint2Info;
            RepoItemInfo _cmblinetypeInfo;
            RepoItemInfo _gbxvisualsInfo;
            RepoItemInfo _btnokInfo;
            RepoItemInfo _openInfo;
            RepoItemInfo _open1Info;
            RepoItemInfo _open2Info;

            /// <summary>
            /// Creates a new LineForm  folder.
            /// </summary>
            public LineFormAppFolder(RepoGenBaseFolder parentFolder) :
                    base("LineForm", "/form[@controlname='LineForm']", parentFolder, 30000, null, true, "c53cc27e-ba70-49ca-8590-b43dd408a86a", "")
            {
                _closeInfo = new RepoItemInfo(this, "Close", "?/?/combobox[@controlname='cmb_colour']/button[@accessiblename='Close']", ".//button[@accessiblename='Close' and @accessiblekeyboardshortcut='Alt+Down Arrow']", 30000, null, "a921ef7d-4217-4348-aeeb-d18439a8e069");
                _gbxpoint2Info = new RepoItemInfo(this, "GbxPoint2", "container[@controlname='gbx_Point2']", "container[@controlname='gbx_Point2']", 30000, null, "f0298c18-6198-4176-bc61-baef72947ad6");
                _cmblinetypeInfo = new RepoItemInfo(this, "CmbLineType", "?/?/combobox[@controlname='cmb_LineType']", "?/?/combobox[@controlname='cmb_LineType']", 30000, null, "dcfb19b5-4570-4370-9499-d763d991b829");
                _gbxvisualsInfo = new RepoItemInfo(this, "GbxVisuals", "container[@controlname='gbx_Visuals']", "container[@controlname='gbx_Visuals']", 30000, null, "ba19c91a-c26f-4c47-8d02-339e89569145");
                _btnokInfo = new RepoItemInfo(this, "BtnOK", "button[@controlname='btn_OK']", "button[@controlname='btn_OK']", 30000, null, "37e3f31c-d848-4829-84a5-6a052f9f045e");
                _openInfo = new RepoItemInfo(this, "Open", "?/?/combobox[@controlname='cmb_colour']/button[@accessiblename='Open']", "?/?/combobox[@controlname='cmb_colour']/button[@accessiblename='Open']", 30000, null, "c856508b-407e-4d1d-a46e-57ef5fb933fc");
                _open1Info = new RepoItemInfo(this, "Open1", "?/?/combobox[@controlname='cmb_LineType']/button[@accessiblename='Open']", ".//button[@accessiblename='Open']", 30000, null, "766362e8-2a36-4e53-a721-4c44bb7c55eb");
                _open2Info = new RepoItemInfo(this, "Open2", "?/?/combobox[@controlname='cmb_LineWidth']/button[@accessiblename='Open']", "?/?/combobox[@controlname='cmb_LineWidth']/button[@accessiblename='Open']", 30000, null, "bc4ebfbf-a9ff-452a-b92d-162b038b90fa");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("c53cc27e-ba70-49ca-8590-b43dd408a86a")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("c53cc27e-ba70-49ca-8590-b43dd408a86a")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Close item.
            /// </summary>
            [RepositoryItem("a921ef7d-4217-4348-aeeb-d18439a8e069")]
            public virtual Ranorex.Button Close
            {
                get
                {
                    return _closeInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Close item info.
            /// </summary>
            [RepositoryItemInfo("a921ef7d-4217-4348-aeeb-d18439a8e069")]
            public virtual RepoItemInfo CloseInfo
            {
                get
                {
                    return _closeInfo;
                }
            }

            /// <summary>
            /// The GbxPoint2 item.
            /// </summary>
            [RepositoryItem("f0298c18-6198-4176-bc61-baef72947ad6")]
            public virtual Ranorex.Container GbxPoint2
            {
                get
                {
                    return _gbxpoint2Info.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The GbxPoint2 item info.
            /// </summary>
            [RepositoryItemInfo("f0298c18-6198-4176-bc61-baef72947ad6")]
            public virtual RepoItemInfo GbxPoint2Info
            {
                get
                {
                    return _gbxpoint2Info;
                }
            }

            /// <summary>
            /// The CmbLineType item.
            /// </summary>
            [RepositoryItem("dcfb19b5-4570-4370-9499-d763d991b829")]
            public virtual Ranorex.ComboBox CmbLineType
            {
                get
                {
                    return _cmblinetypeInfo.CreateAdapter<Ranorex.ComboBox>(true);
                }
            }

            /// <summary>
            /// The CmbLineType item info.
            /// </summary>
            [RepositoryItemInfo("dcfb19b5-4570-4370-9499-d763d991b829")]
            public virtual RepoItemInfo CmbLineTypeInfo
            {
                get
                {
                    return _cmblinetypeInfo;
                }
            }

            /// <summary>
            /// The GbxVisuals item.
            /// </summary>
            [RepositoryItem("ba19c91a-c26f-4c47-8d02-339e89569145")]
            public virtual Ranorex.Container GbxVisuals
            {
                get
                {
                    return _gbxvisualsInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The GbxVisuals item info.
            /// </summary>
            [RepositoryItemInfo("ba19c91a-c26f-4c47-8d02-339e89569145")]
            public virtual RepoItemInfo GbxVisualsInfo
            {
                get
                {
                    return _gbxvisualsInfo;
                }
            }

            /// <summary>
            /// The BtnOK item.
            /// </summary>
            [RepositoryItem("37e3f31c-d848-4829-84a5-6a052f9f045e")]
            public virtual Ranorex.Button BtnOK
            {
                get
                {
                    return _btnokInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The BtnOK item info.
            /// </summary>
            [RepositoryItemInfo("37e3f31c-d848-4829-84a5-6a052f9f045e")]
            public virtual RepoItemInfo BtnOKInfo
            {
                get
                {
                    return _btnokInfo;
                }
            }

            /// <summary>
            /// The Open item.
            /// </summary>
            [RepositoryItem("c856508b-407e-4d1d-a46e-57ef5fb933fc")]
            public virtual Ranorex.Button Open
            {
                get
                {
                    return _openInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Open item info.
            /// </summary>
            [RepositoryItemInfo("c856508b-407e-4d1d-a46e-57ef5fb933fc")]
            public virtual RepoItemInfo OpenInfo
            {
                get
                {
                    return _openInfo;
                }
            }

            /// <summary>
            /// The Open1 item.
            /// </summary>
            [RepositoryItem("766362e8-2a36-4e53-a721-4c44bb7c55eb")]
            public virtual Ranorex.Button Open1
            {
                get
                {
                    return _open1Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Open1 item info.
            /// </summary>
            [RepositoryItemInfo("766362e8-2a36-4e53-a721-4c44bb7c55eb")]
            public virtual RepoItemInfo Open1Info
            {
                get
                {
                    return _open1Info;
                }
            }

            /// <summary>
            /// The Open2 item.
            /// </summary>
            [RepositoryItem("bc4ebfbf-a9ff-452a-b92d-162b038b90fa")]
            public virtual Ranorex.Button Open2
            {
                get
                {
                    return _open2Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Open2 item info.
            /// </summary>
            [RepositoryItemInfo("bc4ebfbf-a9ff-452a-b92d-162b038b90fa")]
            public virtual RepoItemInfo Open2Info
            {
                get
                {
                    return _open2Info;
                }
            }
        }

        /// <summary>
        /// The List1000AppFolder folder.
        /// </summary>
        [RepositoryFolder("9787436e-a8b0-4425-b2b2-31b65405ebec")]
        public partial class List1000AppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _listitem06Info;
            RepoItemInfo _ff0000ffInfo;
            RepoItemInfo _ffff0000Info;
            RepoItemInfo _ff009900Info;
            RepoItemInfo _brokendashInfo;
            RepoItemInfo _listitem035Info;
            RepoItemInfo _listitemcgmInfo;

            /// <summary>
            /// Creates a new List1000  folder.
            /// </summary>
            public List1000AppFolder(RepoGenBaseFolder parentFolder) :
                    base("List1000", "/list[@controlid='1000']", parentFolder, 30000, null, true, "9787436e-a8b0-4425-b2b2-31b65405ebec", "")
            {
                _listitem06Info = new RepoItemInfo(this, "ListItem06", "listitem[@text='0.6']", "listitem[@text='0.6']", 30000, null, "d2c2dffe-ded1-49f6-80c7-8680cd65999b");
                _ff0000ffInfo = new RepoItemInfo(this, "Ff0000ff", "listitem[@text='ff0000ff']", "listitem[@text='ff0000ff']", 30000, null, "b693619e-3f2e-465b-bf4b-dac8cadf817a");
                _ffff0000Info = new RepoItemInfo(this, "Ffff0000", "listitem[@text='ffff0000']", "listitem[@text='ffff0000']", 30000, null, "f621c08f-9217-4173-ab1e-e50dd8eb3f39");
                _ff009900Info = new RepoItemInfo(this, "Ff009900", "listitem[@text=$ColorSelection]", "", 30000, null, "a8ae6104-f3bb-493c-b5c3-399d6385b665");
                _brokendashInfo = new RepoItemInfo(this, "BrokenDash", "listitem[@text=$LineTypeSelection]", "", 30000, null, "cf80b781-032b-49f4-aa0e-878dae04ad53");
                _listitem035Info = new RepoItemInfo(this, "ListItem035", "listitem[@text=$LineWidth]", "", 30000, null, "a661b0cf-d17d-4e8f-8e7a-e55a60602d52");
                _listitemcgmInfo = new RepoItemInfo(this, "ListItemCGM", "listitem[@text='CGM']", "listitem[@text='CGM']", 30000, null, "037d22c5-4f61-4c09-8d08-2e69623c38da");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("9787436e-a8b0-4425-b2b2-31b65405ebec")]
            public virtual Ranorex.List Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.List>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("9787436e-a8b0-4425-b2b2-31b65405ebec")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ListItem06 item.
            /// </summary>
            [RepositoryItem("d2c2dffe-ded1-49f6-80c7-8680cd65999b")]
            public virtual Ranorex.ListItem ListItem06
            {
                get
                {
                    return _listitem06Info.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The ListItem06 item info.
            /// </summary>
            [RepositoryItemInfo("d2c2dffe-ded1-49f6-80c7-8680cd65999b")]
            public virtual RepoItemInfo ListItem06Info
            {
                get
                {
                    return _listitem06Info;
                }
            }

            /// <summary>
            /// The Ff0000ff item.
            /// </summary>
            [RepositoryItem("b693619e-3f2e-465b-bf4b-dac8cadf817a")]
            public virtual Ranorex.ListItem Ff0000ff
            {
                get
                {
                    return _ff0000ffInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The Ff0000ff item info.
            /// </summary>
            [RepositoryItemInfo("b693619e-3f2e-465b-bf4b-dac8cadf817a")]
            public virtual RepoItemInfo Ff0000ffInfo
            {
                get
                {
                    return _ff0000ffInfo;
                }
            }

            /// <summary>
            /// The Ffff0000 item.
            /// </summary>
            [RepositoryItem("f621c08f-9217-4173-ab1e-e50dd8eb3f39")]
            public virtual Ranorex.ListItem Ffff0000
            {
                get
                {
                    return _ffff0000Info.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The Ffff0000 item info.
            /// </summary>
            [RepositoryItemInfo("f621c08f-9217-4173-ab1e-e50dd8eb3f39")]
            public virtual RepoItemInfo Ffff0000Info
            {
                get
                {
                    return _ffff0000Info;
                }
            }

            /// <summary>
            /// The Ff009900 item.
            /// </summary>
            [RepositoryItem("a8ae6104-f3bb-493c-b5c3-399d6385b665")]
            public virtual Ranorex.ListItem Ff009900
            {
                get
                {
                    return _ff009900Info.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The Ff009900 item info.
            /// </summary>
            [RepositoryItemInfo("a8ae6104-f3bb-493c-b5c3-399d6385b665")]
            public virtual RepoItemInfo Ff009900Info
            {
                get
                {
                    return _ff009900Info;
                }
            }

            /// <summary>
            /// The BrokenDash item.
            /// </summary>
            [RepositoryItem("cf80b781-032b-49f4-aa0e-878dae04ad53")]
            public virtual Ranorex.ListItem BrokenDash
            {
                get
                {
                    return _brokendashInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The BrokenDash item info.
            /// </summary>
            [RepositoryItemInfo("cf80b781-032b-49f4-aa0e-878dae04ad53")]
            public virtual RepoItemInfo BrokenDashInfo
            {
                get
                {
                    return _brokendashInfo;
                }
            }

            /// <summary>
            /// The ListItem035 item.
            /// </summary>
            [RepositoryItem("a661b0cf-d17d-4e8f-8e7a-e55a60602d52")]
            public virtual Ranorex.ListItem ListItem035
            {
                get
                {
                    return _listitem035Info.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The ListItem035 item info.
            /// </summary>
            [RepositoryItemInfo("a661b0cf-d17d-4e8f-8e7a-e55a60602d52")]
            public virtual RepoItemInfo ListItem035Info
            {
                get
                {
                    return _listitem035Info;
                }
            }

            /// <summary>
            /// The ListItemCGM item.
            /// </summary>
            [RepositoryItem("037d22c5-4f61-4c09-8d08-2e69623c38da")]
            public virtual Ranorex.ListItem ListItemCGM
            {
                get
                {
                    return _listitemcgmInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The ListItemCGM item info.
            /// </summary>
            [RepositoryItemInfo("037d22c5-4f61-4c09-8d08-2e69623c38da")]
            public virtual RepoItemInfo ListItemCGMInfo
            {
                get
                {
                    return _listitemcgmInfo;
                }
            }
        }

        /// <summary>
        /// The UmlautTecDraw1AppFolder folder.
        /// </summary>
        [RepositoryFolder("a0f5c70e-9db0-439b-b8e9-adeb8b81fb1b")]
        public partial class UmlautTecDraw1AppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _saveInfo;
            RepoItemInfo _exitInfo;

            /// <summary>
            /// Creates a new UmlautTecDraw1  folder.
            /// </summary>
            public UmlautTecDraw1AppFolder(RepoGenBaseFolder parentFolder) :
                    base("UmlautTecDraw1", "/contextmenu[@processname='umlaut TecDraw']", parentFolder, 30000, null, true, "a0f5c70e-9db0-439b-b8e9-adeb8b81fb1b", "")
            {
                _saveInfo = new RepoItemInfo(this, "Save", "menuitem[@accessiblename='Save']", "menuitem[@accessiblename='Save']", 30000, null, "18842db6-8363-4ac8-8493-9808c99a9815");
                _exitInfo = new RepoItemInfo(this, "Exit", "menuitem[@accessiblename='Exit']", "menuitem[@accessiblename='Exit']", 30000, null, "9fa4e290-53a2-4d97-b804-32889ba4a0e8");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("a0f5c70e-9db0-439b-b8e9-adeb8b81fb1b")]
            public virtual Ranorex.ContextMenu Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.ContextMenu>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("a0f5c70e-9db0-439b-b8e9-adeb8b81fb1b")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Save item.
            /// </summary>
            [RepositoryItem("18842db6-8363-4ac8-8493-9808c99a9815")]
            public virtual Ranorex.MenuItem Save
            {
                get
                {
                    return _saveInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The Save item info.
            /// </summary>
            [RepositoryItemInfo("18842db6-8363-4ac8-8493-9808c99a9815")]
            public virtual RepoItemInfo SaveInfo
            {
                get
                {
                    return _saveInfo;
                }
            }

            /// <summary>
            /// The Exit item.
            /// </summary>
            [RepositoryItem("9fa4e290-53a2-4d97-b804-32889ba4a0e8")]
            public virtual Ranorex.MenuItem Exit
            {
                get
                {
                    return _exitInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The Exit item info.
            /// </summary>
            [RepositoryItemInfo("9fa4e290-53a2-4d97-b804-32889ba4a0e8")]
            public virtual RepoItemInfo ExitInfo
            {
                get
                {
                    return _exitInfo;
                }
            }
        }

        /// <summary>
        /// The SaveAppFolder folder.
        /// </summary>
        [RepositoryFolder("d9e9eb8d-7834-4143-a7a2-8fe6701a060d")]
        public partial class SaveAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _dropdownInfo;
            RepoItemInfo _text1001Info;
            RepoItemInfo _buttonsaveInfo;

            /// <summary>
            /// Creates a new Save  folder.
            /// </summary>
            public SaveAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Save", "/form[@title='Save']", parentFolder, 30000, null, true, "d9e9eb8d-7834-4143-a7a2-8fe6701a060d", "")
            {
                _dropdownInfo = new RepoItemInfo(this, "DropDown", "element[@class='DUIViewWndClassName']//combobox[@class='ComboBox']/button[@automationid='DropDown']", ".//button[@automationid='DropDown']", 30000, null, "88440571-2ef0-46cc-b5f4-eed4269ab2ec");
                _text1001Info = new RepoItemInfo(this, "Text1001", "element[@class='DUIViewWndClassName']//combobox[@class='ComboBox']/text[@controlid='1001']", ".//text[@controlid='1001']", 30000, null, "af2582dc-170f-4dec-ad54-b7730c3149c3");
                _buttonsaveInfo = new RepoItemInfo(this, "ButtonSave", "button[@text='&Save']", "button[@text='&Save']", 30000, null, "89be38a7-7e25-4984-8527-0216886b133c");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("d9e9eb8d-7834-4143-a7a2-8fe6701a060d")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("d9e9eb8d-7834-4143-a7a2-8fe6701a060d")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The DropDown item.
            /// </summary>
            [RepositoryItem("88440571-2ef0-46cc-b5f4-eed4269ab2ec")]
            public virtual Ranorex.Button DropDown
            {
                get
                {
                    return _dropdownInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The DropDown item info.
            /// </summary>
            [RepositoryItemInfo("88440571-2ef0-46cc-b5f4-eed4269ab2ec")]
            public virtual RepoItemInfo DropDownInfo
            {
                get
                {
                    return _dropdownInfo;
                }
            }

            /// <summary>
            /// The Text1001 item.
            /// </summary>
            [RepositoryItem("af2582dc-170f-4dec-ad54-b7730c3149c3")]
            public virtual Ranorex.Text Text1001
            {
                get
                {
                    return _text1001Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Text1001 item info.
            /// </summary>
            [RepositoryItemInfo("af2582dc-170f-4dec-ad54-b7730c3149c3")]
            public virtual RepoItemInfo Text1001Info
            {
                get
                {
                    return _text1001Info;
                }
            }

            /// <summary>
            /// The ButtonSave item.
            /// </summary>
            [RepositoryItem("89be38a7-7e25-4984-8527-0216886b133c")]
            public virtual Ranorex.Button ButtonSave
            {
                get
                {
                    return _buttonsaveInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonSave item info.
            /// </summary>
            [RepositoryItemInfo("89be38a7-7e25-4984-8527-0216886b133c")]
            public virtual RepoItemInfo ButtonSaveInfo
            {
                get
                {
                    return _buttonsaveInfo;
                }
            }
        }

        /// <summary>
        /// The BatchConverterFormAppFolder folder.
        /// </summary>
        [RepositoryFolder("95d8ea81-897e-4b08-b2c0-b911cb120c2e")]
        public partial class BatchConverterFormAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _openInfo;
            RepoItemInfo _open1Info;

            /// <summary>
            /// Creates a new BatchConverterForm  folder.
            /// </summary>
            public BatchConverterFormAppFolder(RepoGenBaseFolder parentFolder) :
                    base("BatchConverterForm", "/form[@controlname='BatchConverterForm']", parentFolder, 30000, null, true, "95d8ea81-897e-4b08-b2c0-b911cb120c2e", "")
            {
                _openInfo = new RepoItemInfo(this, "Open", "?/?/combobox[@controlname='cmb_ConvertFrom']/button[@accessiblename='Open']", ".//button[@accessiblename='Open']", 30000, null, "ec147d13-1182-4dc9-9d62-67d5bb5187fb");
                _open1Info = new RepoItemInfo(this, "Open1", "?/?/combobox[@controlname='cmb_ConvertTo']/button[@accessiblename='Open']", "?/?/combobox[@controlname='cmb_ConvertTo']/button[@accessiblename='Open']", 30000, null, "d2025420-bbfe-4d4a-a5b4-4a57b5c85c84");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("95d8ea81-897e-4b08-b2c0-b911cb120c2e")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("95d8ea81-897e-4b08-b2c0-b911cb120c2e")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Open item.
            /// </summary>
            [RepositoryItem("ec147d13-1182-4dc9-9d62-67d5bb5187fb")]
            public virtual Ranorex.Button Open
            {
                get
                {
                    return _openInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Open item info.
            /// </summary>
            [RepositoryItemInfo("ec147d13-1182-4dc9-9d62-67d5bb5187fb")]
            public virtual RepoItemInfo OpenInfo
            {
                get
                {
                    return _openInfo;
                }
            }

            /// <summary>
            /// The Open1 item.
            /// </summary>
            [RepositoryItem("d2025420-bbfe-4d4a-a5b4-4a57b5c85c84")]
            public virtual Ranorex.Button Open1
            {
                get
                {
                    return _open1Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Open1 item info.
            /// </summary>
            [RepositoryItemInfo("d2025420-bbfe-4d4a-a5b4-4a57b5c85c84")]
            public virtual RepoItemInfo Open1Info
            {
                get
                {
                    return _open1Info;
                }
            }
        }

    }
#pragma warning restore 0436
}
